#!/usr/bin/env python
import sys
import webbrowser
from urllib.parse import quote

if __name__ == "__main__":
    search_url = "http://www.google.com/?#q="
    try:
        query = " ".join(sys.argv[1:])
        query = quote(query)
        webbrowser.open_new_tab(search_url + query)
    except IndexError:
        webbrowser.open_new_tab("www.google.com")
